#!/bin/bash

gcc -g -Wall -std=gnu99 -o keygen keygen.c

gcc -g -Wall -std=gnu99 -o otp_enc_d otp_enc_d.c encrypt_pool.c -lpthread

gcc -g -Wall -std=gnu99 -o otp_enc otp_enc.c

gcc -g -Wall -std=gnu99 -o otp_dec_d otp_dec_d.c decrypt_pool.c -lpthread

gcc -g -Wall -std=gnu99 -o otp_dec otp_dec.c
